services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2@sha256:753eeb0cc22ab7baad39ed47cbd1aae14e193dd1b264e965f193a9ea1d1e1bdd
    container_name: index
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./icons:/app/public/icons
    environment:
      HOMEPAGE_ALLOWED_HOSTS: index.rezoleo.fr # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    restart: always
    mem_limit: 250M
    cpus: 0.50
