---
- name: Copy docker compose file
  ansible.builtin.copy:
    src: compose.yml
    dest: /home/docker/compose.yml
    owner: docker
    group: docker
    mode: "0644"

- name: Start docker compose
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /home/docker
  changed_when: true
