# Compose file for running paperless from the Github Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'compose.yml' and the files 'docker-compose.env'
#   and 'paperless.env' into a folder.
# - Run 'podman compose pull'.
# - Run 'podman compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.
services:
  broker:
    image: docker.io/library/redis:8@sha256:a7efd4ed5037dcfe1543c0e50b9f06293d3e88827005544bf37f381eea5f01cf
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - paperless_net
    mem_limit: 250M
    cpus: 0.50

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:3.0@sha256:65a4cabf0169ea7fbd90ab7bb28ba3f8b5909613635acda1a03ad606f34b456b
    restart: always
    depends_on:
      - broker
    ports:
      - "3002:8000"
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
    env_file: paperless.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
    networks:
      - paperless_net
    mem_limit: 750M
    cpus: 1

volumes:
  redisdata:

networks:
  paperless_net:
    driver: bridge
    x-podman:
      dns_enabled: true
