- name: Copy docker compose file
  ansible.builtin.copy:
    src: compose.yml
    dest: /home/docker/compose.yml
    owner: docker
    group: docker
    mode: "0644"

- name: Create gethomepage config directory
  ansible.builtin.copy:
    src: config/
    dest: /home/docker/config
    owner: docker
    group: docker
    mode: "0755"

- name: Create gethomepage icons directory
  ansible.builtin.copy:
    src: icons/
    dest: /home/docker/icons
    owner: docker
    group: docker
    mode: "0755"

- name: Start gethomepage
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /home/docker
  changed_when: true

- name: Add firewall rule for port 3000
  ansible.builtin.import_role:
    name: firewall
    tasks_from: create_rule.yml
  vars:
    firewall_rules:
      050-equestria:
        - rule_name: "Allow traffic from Equestria"
          chain: INPUT
          source: 10.12.2.2/32 # IP of Equestria
          protocol: tcp
          destination_port: 3000
          target: ACCEPT
