- name: Installing podman
  ansible.builtin.apt:
    update_cache: true
    name:
      - podman
      - podman-compose
      - uidmap
    state: present

- name: Create podman group
  ansible.builtin.group:
    name: "podman"
    system: true

- name: Add ansible user to podman group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "podman"
    append: true

- name: Create podman user
  ansible.builtin.user:
    name: "podman"
    group: "podman"
    system: true
    create_home: true

- name: Add podman user to systemd-journal group
  ansible.builtin.user:
    name: "podman"
    groups: systemd-journal
    append: true


- name: Add podman user to subuid file
  ansible.builtin.lineinfile:
    path: /etc/subuid
    regexp: "^podman:.*"
    line: "podman:10000:55536"
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Add podman group to subgid file
  ansible.builtin.lineinfile:
    path: /etc/subgid
    regexp: "^podman:.*"
    line: "podman:10000:55536"
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Enable lingering for podman user
  ansible.builtin.command:
    cmd: "loginctl enable-linger podman"
    creates: "/var/lib/systemd/linger/podman"

- name: Enable rootless mode for podman
  ansible.builtin.command:
    cmd: podman system migrate
  become: true
  become_user: podman
  changed_when: true

##### Podman compose #####

### BentoPDF ###

- name: Create bentokae directory
  ansible.builtin.file:
    path: /home/podman/bentokae
    state: directory
    owner: podman
    group: podman
    mode: "0755"

- name: Copy compose file for bentopdf
  ansible.builtin.copy:
    src: bentokae/compose.yml
    dest: /home/podman/bentokae/compose.yml
    owner: podman
    group: podman
    mode: "0644"

### Index ###

- name: Create index directory
  ansible.builtin.file:
    path: /home/podman/index
    state: directory
    owner: podman
    group: podman
    mode: "0755"

- name: Create gethomepage config directory
  ansible.builtin.copy:
    src: index/config/
    dest: /home/podman/index/config
    owner: podman
    group: podman
    mode: "0755"

- name: Create gethomepage icons directory
  ansible.builtin.copy:
    src: index/icons/
    dest: /home/podman/index/icons
    owner: podman
    group: podman
    mode: "0755"

- name: Copy compose file for index
  ansible.builtin.copy:
    src: index/compose.yml
    dest: /home/podman/index/compose.yml
    owner: podman
    group: podman
    mode: "0644"

##### Start services #####

- name: Start index
  ansible.builtin.command:
    cmd: podman-compose up -d
    chdir: /home/podman/index
  become: true
  become_user: podman
  register: hestia_compose_index
  changed_when: hestia_compose_index.stdout != ""

- name: Start bentopdf
  ansible.builtin.command:
    cmd: podman-compose up -d
    chdir: /home/podman/bentokae
  become: true
  become_user: podman
  register: hestia_compose_bentopdf
  changed_when: hestia_compose_bentopdf.stdout != ""

- name: Add firewall rules for Hestia services
  ansible.builtin.import_role:
    name: firewall
    tasks_from: create_rule.yml
  vars:
    firewall_rules:
      050-equestria:
        - rule_name: "Allow traffic from Equestria to port 3000"
          chain: INPUT
          protocol: tcp
          source: 192.168.122.1/32
          destination_port: 3000
          target: ACCEPT
        - rule_name: "Allow traffic from Equestria to port 3001"
          chain: INPUT
          protocol: tcp
          source: 192.168.122.1/32
          destination_port: 3001
          target: ACCEPT
