keepalived_interface: eth0
keepalived_advert_int: 1
keepalived_priority_master: 150
keepalived_priority_backup: 100
keepalived_script_user: keepalived_script
keepalived_check_script: ""
keepalived_check_script_path: /usr/local/bin/keepalived_check.sh
keepalived_check_interval: 2
keepalived_check_fall: 2
keepalived_check_rise: 2

# Host example for dns with keepalived
# Uncomment and define based on your actual VIPs, router IDs, and host names:
# keepalived_peer_group: dns_resolvers
# Add a password in both machines
# keepalived_auth_pass: ""
# keepalived_vips:
#    - vip: 1.2.3.4
#      master: server name 1
#      router_id: 12
