- name: Retrieve Nextcloud secrets from Vault
  community.hashi_vault.vault_kv2_get:
    path: services/nextcloud
  register:
    nextcloud_admin_username: _task.result.secret.admin_username
    nextcloud_admin_password: _task.result.secret.admin_password
    nextcloud_smtp_password: _task.result.secret.smtp_password
    nextcloud_smtp_address: _task.result.secret.smtp_address
    nextcloud_object_key: _task.result.secret.object_key
    nextcloud_object_secret: _task.result.secret.object_secret
  run_once: true
  delegate_to: localhost
  become: false
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

- name: Retrieve db secrets from Vault
  community.hashi_vault.vault_kv2_get:
    path: databases/nextcloud@pg.rezoleo.fr
  register:
    nextcloud_db_password: _task.result.secret.nextcloud
  run_once: true
  delegate_to: localhost
  become: false
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

- name: Create nextcloud directory
  ansible.builtin.file:
    path: /home/podman/nextcloud
    state: directory
    owner: podman
    group: podman
    mode: "0755"
  become: true

- name: Copy compose file for paperless
  ansible.builtin.copy:
    src: paperless/compose.yml
    dest: /home/podman/nextcloud/compose.yml
    owner: podman
    group: podman
    mode: "0644"
  become: true

- name: Copy and fill .env file for paperless
  ansible.builtin.template:
    src: nextcloud.env.j2
    dest: /home/podman/paperless/nextcloud.env
    owner: podman
    group: podman
    mode: "0600"
  become: true

- name: Start nextcloud
  ansible.builtin.command:
    cmd: podman-compose up -d
    chdir: /home/podman/nextcloud
  become: true
  become_user: podman
  changed_when: true


- name: Add firewall rules for Hestia services
  ansible.builtin.import_role:
    name: firewall
    tasks_from: create_rule.yml
  vars:
    firewall_rules:
      050-equestria:
        - rule_name: "Allow traffic from Equestria to port 3000"
          chain: INPUT
          protocol: tcp
          source: 10.12.2.2/32 # TODO: Source IP should depend on the inventory
          destination_port: 3000
          target: ACCEPT
