# Podman rooltess requires lingering, this is not usually available using CT
# thus this structure catches this issue and prevent the role from failing without explanations.

- name: Fail if run on CT
  ansible.builtin.fail:
    msg: "Podman rootless can only be installed on a VM, don't use this role on a CT!"
  when: ansible_virtualization_type == 'lxc'

- name: Install and configure Podman
  ansible.builtin.include_tasks:
    file: podman.yml
  when: ansible_virtualization_type != 'lxc'
