services:
  nextcloud:
    image: nextcloud:35.0.1-apache
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./nextcloud:/var/www/html
    networks:
      - nextcloud_net
    env_file: nextcloud.env
    mem_limit: 8G
    cpus: 4
    healthcheck:
      test: curl -sSf 'http://localhost/status.php' | grep '"installed":true' | grep '"maintenance":false' | grep '"needsDbUpgrade":false' || exit 1
      interval: 60s
      start_period: 120s
      timeout: 5s
      retries: 10
    depends_on:
      broker:
        condition: service_healthy

  broker:
    image: docker.io/library/redis:8@sha256:a7efd4ed5037dcfe1543c0e50b9f06293d3e88827005544bf37f381eea5f01cf
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - nextcloud_net
    mem_limit: 1G
    cpus: 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "5s"

volumes:
  redisdata:

networks:
  nextcloud_net:
    driver: bridge
    x-podman:
      dns_enabled: true
