---
- name: Install required packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - uidmap
      - ca-certificates
    state: present

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    mode: "0755"
    state: directory

- name: Add docker's official GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: amd64 # Valeur fixée à la main
    signed_by: /etc/apt/keyrings/docker.asc

- name: Install docker and docker-compose
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-ce-rootless-extras # Required for rootless mode
    state: present

- name: Create docker user with reduced privileges
  ansible.builtin.user:
    name: docker
    create_home: true
    state: present
    uid: 1001
