---
- name: Deploy a new server
  hosts: all
  roles:
    # - common
    - firewall
    - monitoring
    - role: ntp
      when: ansible_virtualization_type != "lxc"
    - ssh
    - podman
    - hestia

- name: Deploy UPS monitoring
  hosts: ups
  become: true
  roles:
    - nut
