---
- name: Deploy a new server
  hosts: all
  become: true
  roles:
    - common
    - firewall
    # - monitoring
    # - role: ntp
    #   when: ansible_virtualization_type != "lxc"
    - ssh
    - hestia

- name: Deploy UPS monitoring
  hosts: ups
  become: true
  roles:
    - nut
